### PR TITLE
fix: propagate stderr from `setClock` on failure

### PR DESCRIPTION
**Pull request by eventualbuddha**
Now trying to set the clock while NTP is on will yield this sensible error message:

Untitled

### CODE REVIEW

**Comment by benadida** [comment]
This is already done in the machine lockdown script. Are we sure we want to do this in kiosk-browser too, where it will then affect our dev machines?

**Comment by eventualbuddha** [comment]
> This is already done in the machine lockdown script. Are we sure we want to do this in kiosk-browser too, where it will then affect our dev machines?

Depends. Without this the feature to set the clock just fails altogether. An alternative would be to detect this condition and log a helpful error message telling you how to fix it.

Also, in my testing there's yet another time sync feature provided by Parallels that happens regardless of whether NTP is enabled, so we'll probably need to document that somewhere.

**Comment by benadida** [comment]
> Depends. Without this the feature to set the clock just fails altogether. An alternative would be to detect this condition and log a helpful error message telling you how to fix it.

Agree with logging.

My gut is that we're going to get grumpy if time sync turns off on us in dev just by trying out this feature, so I think logging is probably best.

**Comment by eventualbuddha** [comment]
@benadida ready for review again

**Review by benadida — APPROVED** [review]

**Pull request merged**
